name: AdminActivityTracker
version: '${version}'
main: dev.pvpshiba.adminActivityTracker.Main
api-version: '1.21'
authors: [ 303pvpshiba ]

permissions:
  aat.admin:
    description: A player who has this permission is tracked by the plugin.
    default: op