name: AdminActivityTracker
version: '${version}'
main: uwu.itsshiba.adminactivitytracker.Main
api-version: '1.20'
authors: [ ItsShiba ]
website: riftmc.eu

permissions:
  aat.admin:
    description: A player who has this permission is tracked by the plugin.
    default: op